### ISSUE TITLE
Logging Rename Refactorings using the in-place editor causes exceptions to be thrown from the JavaModel

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#102]
<code>
Java Model Exception: Java Model Status [main2(String[]) [in Hellox [in [Working copy] Hellox.java [in <default> [in src [in Hello]]]]] does not exist]
    at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:492)
    at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:526)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:252)
    at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:238)
    at org.eclipse.jdt.internal.core.Member.getFlags(Member.java:164)
    at org.eclipse.jdt.internal.corext.refactoring.rename.RenameMethodProcessor.createRefactoringDescriptor(RenameMethodProcessor.java:728)
    at org.eclipse.jdt.internal.corext.refactoring.rename.JavaRenameProcessor.getSimpleRefactoringDescriptor(JavaRenameProcessor.java:97)
    at org.eclipse.ltk.core.refactoring.participants.RenameRefactoring.getSimpleRefactoringDescriptor(RenameRefactoring.java:59)
    at org.eclipse.ltk.ui.refactoring.RefactoringWizard.logRefactoringEvent(RefactoringWizard.java:683)
    at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.logRefactoring(RefactoringExecutionHelper.java:145)
    at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:242)
    at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:179)
    at org.eclipse.jdt.ui.refactoring.RenameSupport.perform(RenameSupport.java:197)
    at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.doRename(RenameLinkedMode.java:361)
    at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode$EditorSynchronizer.left(RenameLinkedMode.java:119)
    at org.eclipse.jface.text.link.LinkedModeModel.exit(LinkedModeModel.java:341)
    at org.eclipse.jface.text.link.LinkedModeUI$4.run(LinkedModeUI.java:1194)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3586)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3279)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2629)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2593)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2427)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:670)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:663)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
</code>

The same scenario does not happen when we use capture the code through the RefactoringWizard interface. _Why?_

**Comment by vazexqi** [comment]
Fixed in 751b0b085623a0307565b9bce471ac291edce770

We were capturing the refactoring descriptor too late after the change has been done.
