### ISSUE TITLE
Keep the repository clean by generating fewer workspace IDs

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#105]
As of 11/9/2010, CodingSpectator has registered 23, 30 and 30 workspaces in the repository for me, Stas and Nick, respectively. A lot of these workspace ID's are generated when we are testing CodingSpectator through Eclipse. We can reduce this clutter by generating a fixed UUID (all zeros) when running CodingSpectator in DEBUG_MODE.

**Comment by reprogrammer** [comment]
2eafa0c1f7bf215512f9c78aa771475f4d845ee6 generates an all zero UUID when run in test or debug mode. Because this behavior keeps reusing this specific UUID, we get the following exception if we don't deleted the all-zeros UUID from the repository before importing it. This deletion can be automated easily. But, it hasn't been automated yet.

<pre>
edu.illinois.codingspectator.monitor.ui.submission.Submitter$InitializationException: org.tmatesoft.svn.core.SVNException: svn: Path '/svn/CodingSpectatorData/username/00000000-0000-0000-0000-000000000000/1.0.0.qualifier' already exists
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.authenticateAndInitialize(Submitter.java:73)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.promptUntilValidCredentialsOrCanceled(Submitter.java:140)
    at edu.illinois.codingspectator.monitor.ui.Uploader.promptUntilValidCredentialsOrCanceled(Uploader.java:39)
    at edu.illinois.codingspectator.monitor.ui.WorkbenchPreferencePage$1.widgetSelected(WorkbenchPreferencePage.java:89)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3540)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3161)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
    at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:65)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3540)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3161)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
Caused by: org.tmatesoft.svn.core.SVNException: svn: Path '/svn/CodingSpectatorData/username/00000000-0000-0000-0000-000000000000/1.0.0.qualifier' already exists
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
    at org.tmatesoft.svn.core.internal.io.dav.DAVCommitEditor.addDir(DAVCommitEditor.java:171)
    at org.tmatesoft.svn.core.wc.SVNCommitClient.importDir(SVNCommitClient.java:1495)
    at org.tmatesoft.svn.core.wc.SVNCommitClient.doImport(SVNCommitClient.java:698)
    at edu.illinois.codingspectator.monitor.core.submission.SVNManager.doImport(SVNManager.java:100)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.authenticateAndInitialize(Submitter.java:67)
    ... 41 more
</pre>

**Comment by reprogrammer** [comment]
I suggest to use the assembla repository when run in testing or debug mode, specially because of the huge files that might get into the repository because of testing issue #113.

Reloved in 9bbdd027682d64e76370714370b4ea36c1142745.
