### ISSUE TITLE
Write automated tests for watched refactoring processors

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#124]
The processors of the following refactorings implement `IWatchedProcessor`.
1. JavaMove
2. MoveInstanceMethod
3. MoveStaticMembers
4. RenameCompilationUnit
5. RenameEnumConst
6. RenameJavaProject
7. RenameLocalVariable
8. RenameNonVirtualMethod
9. RenameVirtualMethod
10. RenamePackageProcessor
11. RenameSourceFolder
12. RenameTypeParameter
13. RenameType

Among the above refactorings, the following refactorings override `instantiateDelegate()`.
1. JavaMove
2. MoveInstanceMethod
3. MoveStaticMember
4. RenameCompilationUnit

Ideally, we'll have automated tests for all the processor based refactorings. But, it would take some time to automate all the tests. So, I'd suggest to automate the ones whose instrumentation is more complicated, i.e. the ones that implement `instantiateDelegate()`. We've already written an automated test for RenameCompilationUnit (issue #122). So, I suggest to automate the tests for the following three refactorings.
1. JavaMove
2. MoveInstanceMethod
3. MoveStaticMember

After writing automated tests for the above three refactorings, we'll release a new version of CodingSpectator that contains our fix for issue #118.

**Comment by reprogrammer** [comment]
Wrote a total of six automated tests for MoveInstanceMethod and MoveStaticMember in 3fe78f37a1097cf6637b6b9bff6bc3a3dddfe44d .. 3eeed9ef4569d7bfc34835cd4679bf8c29ed3432.

**Comment by reprogrammer** [comment]
`JavaMoveProcessor` has a field of type `IMovePolicy`. And, `IMovePolicy` is implemented by the following classes.
1. `MoveFilesFoldersAndCusPolicy`
2. `MovePackageFragmentRootsPolicy`
3. `MovePackagesPolicy`
4. `MoveSubCuElementsPolicy`
5. `MoveImportDeclarationsPolicy`
6. `MoveMembersPolicy`
7. `NoMovePolicy`

Since CodingSpectator hasn't changed any of these polices, I'll write a test for only one of them for now. We'll add more tests in future.

**Comment by reprogrammer** [comment]
debfcf489939d42fa7c7cd7a4e601171439a8213 adds a test for part of `MoveFilesFoldersAndCusPolicy`.

**Comment by rajkuma1** [comment]
Added a test for Rename Source Folder in de0882fa2184c0429dcfcea4f35d5e43dc10651d.

**Comment by rajkuma1** [comment]
Added a test for Rename Local Variable in 5520a6092ebe988292e42a885a0dc18eb767e46f  .. b77bb488eda591fd9385a783559693e08f621d78 and 2ba0e7f01a42497d8d6dca19ab9468d89e6b6273.

**Comment by rajkuma1** [comment]
I think it makes more sense to name the test cases with Rename[Non]VirtualMethod to Rename[Non]]OverRiddenMethod. In JAVA, all methods are virtual by default.

**Comment by rajkuma1** [comment]
Added a test for Rename Non Virtual Method in  4d0eac78efd0e427409d242c7cd3fc7e58bb73e2 and eee0d6488ff9f484e5f2a1fa1d835fe9966ca173.

**Comment by rajkuma1** [comment]
Added a test for Rename Virtual Method in 2c8933c1c923b9182399b6c7a50e1ae85c6e00a1.

**Comment by rajkuma1** [comment]
Added a test for Rename Java Project in 52f5a139f006d093bbf1f55486e346ff7905ffef .. 1f03874d53422e2d59b0c6e56ecb3554f74114dd.

**Comment by rajkuma1** [comment]
Updated Rename Non Virtual Method in eee0d6488ff9f484e5f2a1fa1d835fe9966ca173.

**Comment by reprogrammer** [comment]
Balaji said:

> 1. What do you mean by `RenameTypeParameter`? Is it renaming something like `void function(MyClass variable)` to `void function(MyRenamedClass variable)`?
> 2. `RenamePackageProcessor` rename a package like `org.example` to `org.renamedExample`?
> 3. How do I write more than one test case for the same category? Is there a naming convention?

**Comment by reprogrammer** [comment]
Balaji,
1. Just from the name of the processor (`RenameTypeParameter`), I would say, this processor is in charge of renaming generic types, e.g. renaming `C<T1>` to `C<T2>` . However, the best to find out what a particular refactoring does is to consult the source code. For example, the class for `RenameTypeParameter` is `org.eclipse.jdt.internal.corext.refactoring.rename.RenameTypeParameterProcessor`. If you cannot tell what the processor does by reading the soure code, you can insert some break points in the source code and try to invoke the refactoring. If you perform an action that hits the breakpoint, you have found at least one of the changes that the processor performs.
2. I think your guess for `RenamePackageProcessor` is correct. But, you can confirm it by the method I explained above.
3. There is no specific naming convention. The rule is to simply pick intention revealing names. For example, we wrote several tests for pull up. One of them invoked pull up on a class, while the other one invoked it on a field. So, we called them `PullUpSelectedClassTest` and `PullUpSelectedFieldTes`, respectively.

**Comment by rajkuma1** [comment]
Added a test for renaming a class as part of a template argument in 9b7666429488c1a7b903b065e30b8ef3c083bfbf.

**Comment by rajkuma1** [comment]
Added tests for renaming interface type in 1d2720e1ccbaf863446c0938ccf21526996f8957.

**Comment by rajkuma1** [comment]
Added a test for renaming enum constant in a5e2d413bea7be185b830728d795c83cd8725291.

**Comment by rajkuma1** [comment]
Added a test for renaming a source package in a8d44dba9c7bdb5fc59464273f27fa899738d7cc.

**Comment by reprogrammer** [comment]
8193eab39a33b32af67b85610002aaa70bbb3264 .. 0f6e5be29c83e8e496c71d6bbec9cb862289e85c merged the branch "test-rename" into "master".

**Comment by rajkuma1** [comment]
Move refactoring has a bug.

When the destination to move a compilation unit doesn't exist, an exception is thrown as part of getting the refactoring descriptor.

The reason why this happens is because the tool assumes that the destination is always valid which in this test case doesn't hold good:
    protected void doExecuteRefactoring() {
        bot.selectFromPackageExplorer(getProjectName(), "src", "edu.illinois.codingspectator", getTestFileFullName());
        bot.invokeRefactoringFromMenu("Move...");
        bot.activateShellWithName("Move");
        bot.getCurrentTree().pressShortcut(org.eclipse.jface.bindings.keys.KeyStroke.getInstance('.'));
        bot.getCurrentTree().pressShortcut(org.eclipse.jface.bindings.keys.KeyStroke.getInstance('.'));
        bot.clickButtons(IDialogConstants.OK_LABEL, IDialogConstants.OK_LABEL);
    }

Here's the trace:

java.lang.IllegalArgumentException: The map does not contain the attribute 'target'
    at org.eclipse.jdt.internal.core.refactoring.descriptors.JavaRefactoringDescriptorUtil.getString(JavaRefactoringDescriptorUtil.java:182)
    at org.eclipse.jdt.internal.core.refactoring.descriptors.JavaRefactoringDescriptorUtil.getString(JavaRefactoringDescriptorUtil.java:201)
    at org.eclipse.jdt.internal.core.refactoring.descriptors.JavaRefactoringDescriptorUtil.getResourcePath(JavaRefactoringDescriptorUtil.java:370)
    at org.eclipse.jdt.core.refactoring.descriptors.MoveDescriptor.<init>(MoveDescriptor.java:167)
    at org.eclipse.jdt.internal.core.refactoring.descriptors.RefactoringSignatureDescriptorFactory.createMoveDescriptor(RefactoringSignatureDescriptorFactory.java:230)
    at org.eclipse.jdt.internal.corext.refactoring.reorg.ReorgPolicyFactory$MoveFilesFoldersAndCusPolicy.createRefactoringDescriptor(ReorgPolicyFactory.java:1339)
    at org.eclipse.jdt.internal.corext.refactoring.reorg.ReorgPolicyFactory$FilesFoldersAndCusReorgPolicy.getDescriptor(ReorgPolicyFactory.java:898)
    at org.eclipse.jdt.internal.corext.refactoring.reorg.JavaMoveProcessor.createRefactoringDescriptor(JavaMoveProcessor.java:328)
    at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedProcessorDelegate.createRefactoringDescriptor(WatchedProcessorDelegate.java:109)
    at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedProcessorDelegate.getSimpleRefactoringDescriptor(WatchedProcessorDelegate.java:32)
    at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedJavaMoveProcessor.getSimpleRefactoringDescriptor(WatchedJavaMoveProcessor.java:18)
    at org.eclipse.ltk.core.refactoring.participants.MoveRefactoring.getSimpleRefactoringDescriptor(MoveRefactoring.java:71)
    at org.eclipse.ltk.core.refactoring.codingspectator.Logger.createRefactoringDescriptor(Logger.java:43)
    at org.eclipse.ltk.ui.refactoring.RefactoringWizard.performFinish(RefactoringWizard.java:653)
    at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.okPressed(RefactoringWizardDialog2.java:487)
    at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:472)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3540)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3161)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation$1.run(RefactoringWizardOpenOperation.java:186)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:199)
    at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:117)
    at org.eclipse.jdt.internal.ui.refactoring.actions.RefactoringStarter.activate(RefactoringStarter.java:38)
    at org.eclipse.jdt.internal.corext.refactoring.RefactoringExecutionStarter.startMoveRefactoring(RefactoringExecutionStarter.java:400)
    at org.eclipse.jdt.internal.ui.refactoring.reorg.ReorgMoveAction.run(ReorgMoveAction.java:109)
    at org.eclipse.jdt.ui.actions.MoveAction.run(MoveAction.java:150)
    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:274)
    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:250)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3540)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3161)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)

**Comment by rajkuma1** [comment]
Added tests for valid performed and cancelled move of compilation unit to a container in 8c5d4659c8df75ce1dc21020995bcb6f8fd85dd5 .. 0e9309ef0caa04548ec2eab3a80a9a9767b85fec and 87beaf4ac48e81b2ce688b73aaf05a506530a70a.

**Comment by rajkuma1** [comment]
Added tests for MovePackageFragmentRootsPolicy in 1a03d6c60178057e2386d7d0368ec76d6a1407b4. There are RefactoringTest and CodingSpectatorBot related changes in this commit as well.

**Comment by rajkuma1** [comment]
Added tests for:
1. `MovePackagesPolicy` in  46b1316cf9690f8569e5aaa6de0a8fd2166e7d03 .. 477fdcf5d0571e3688de9bca9e8bab7e740e9a63.
2. `MoveSubCuElementsPolicy` in 36e3deea0f2951a60c04c774bb36b98b5a3e05db and 0157d65d43ec5160f2927f05d34ce40ff892b4bd.
3. `MoveImportDeclarationsPolicy` in  dbee4aca2a454879678e8a454949b71620c30f3c and 703248e78ef0bf1d56cc08959cfc48231f46694e.
4. `MoveMembersPolicy` in 926650a78f19f50d59e1fbd16d930176483ede35, a099bc13ed71970b8fc31f0986ffa95722f7f323 and 1546ca2e70c2ae651614a36eb089abefc1b9dbbd.

**Comment by rajkuma1** [comment]
The refactoring descriptor is incomplete. The comment section does not contain the proper description of the IJavaElement being moved.
The fix is to use the Java element directly instead of getting the 

`JavaElementLabels.getTextLabel(fJavaElements[0].getElementName(), JavaElementLabels.ALL_FULLY_QUALIFIED), getDestinationLabel() }) : Messages.format(getHeaderPatternPlural(),`

has to change to 

`JavaElementLabels.getTextLabel(fJavaElements[0], JavaElementLabels.ALL_FULLY_QUALIFIED), getDestinationLabel() }) : Messages.format(getHeaderPatternPlural(),`

in `org.eclipse.jdt.internal.corext.refactoring.reorg.ReorgPolicyFactory.SubCuElementReorgPolicy.getDescriptor()`

**Comment by reprogrammer** [comment]
[As rajkuma1 said](https://github.com/vazexqi/CodingSpectator/issues/124#issue/124/comment/928743), CodingSpectator generates the following value for the attribute "comment" of the descriptor for the test move.T24.

<pre>
"Move element '' to 'edu.illinois.codingspectator.D'
- Original project: 'Prj'
- Destination element: 'edu.illinois.codingspectator.D'
- Original element: 'edu.illinois.codingspectator.E'
- Textual move only
- Update references to refactored element"
</pre>


However, the descriptor above is not complete because it lacks the element being moved. The complete descriptor is the following.

<pre>
"Move element 'edu.illinois.codingspectator.E' to 'edu.illinois.codingspectator.D'
- Original project: 'Prj'
- Destination element: 'edu.illinois.codingspectator.D'
- Original element: 'edu.illinois.codingspectator.E'
- Textual move only
- Update references to refactored element"
</pre>

**Comment by rajkuma1** [comment]
@reprogrammer Can I make the change  and submit it?

**Comment by rajkuma1** [comment]
Mohsen and I verified that [this](https://github.com/vazexqi/CodingSpectator/issues/labels/Assigned%20to%20Balaji#issue/124/comment/931315) is a bug in Eclipse. We tried it on Eclipse Helios SR1 and noticed that Eclipse generates the same value for the comment attribute of the refactoring as the one that CodingSpectator does. This bug exists in other Move policies. However, this problem is not critical because the name of the original element is still mentioned in the part "original element" of the comment and is just left out from the beginning of the comment, which is the summary of the comment.

**Comment by rajkuma1** [comment]
It's NOT possible to test NoMovePolicy. Here's why.
When NoMovePolicy refactoring policy kicks in, the refactoring option is disabled.

`org.eclipse.jdt.internal.corext.refactoring.RefactoringAvailabilityTester.isMoveAvailable(IResource[], IJavaElement[])` checks for `canEnable()` which returns false in the case of NoMovePolicy.

Here are the steps to invoke the NoMovePolicy:
1. Create a project.
2. Select `JRE System Library`.
3. Expand `resources.jar`.
4. Select `com.sun.corba.se.impl.logging` from within that jar.
You cannot see the refacoring menu appear because,

```
if (ReorgUtils.isArchiveOrExternalMember(javaElements) && ReorgUtils.getElementsOfType(javaElements, IJavaElement.PACKAGE_FRAGMENT_ROOT).size() != javaElements.length)
    return NO;
```

returns this policy under `org.eclipse.jdt.internal.corext.refactoring.reorg.ReorgPolicyFactory.createReorgPolicy(boolean, IResource[], IJavaElement[])`

**Comment by rajkuma1** [comment]
926650a78f19f50d59e1fbd16d930176483ede35 brings out a bug in eclipse. When you select multiple fields, only the first field in the textual order is moved. 

```
public class C {
    private int i;
    private int j;
}

class C2 {

}
```

If you select both i and j in C and move it to C2, only i gets moved.
