### ISSUE TITLE
Eclipse startup event raises a compilation problem

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#127]
When the Eclipse starts up, I get the "Problem Occurred" dialog with the following error message.

<pre>
java.lang.Error: Unresolved compilation problem:
The method transferToCodingSpectatorComplete() of type new TransferToCodingSpectatorListener(){} must override a superclass method

at org.eclipse.epp.usagedata.internal.ui.uploaders.AskUserUploader.startBasicTransferToCodingSpectator(AskUserUploader.java:200)
at org.eclipse.epp.usagedata.internal.ui.uploaders.AskUserUploader.startTransferToCodingSpectator(AskUserUploader.java:193)
at org.eclipse.epp.usagedata.internal.recording.uploading.UploadManager.startTransferToCodingSpectator(UploadManager.java:226)
at org.eclipse.epp.usagedata.internal.recording.Startup.earlyStartup(Startup.java:26)
at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:87)
at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:66)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.ui.internal.Workbench$59.run(Workbench.java:2409)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by reprogrammer** [comment]
Resolved in 6fc58ed72129a04ba3b089c0b91dc39bb762b518.
