### ISSUE TITLE
Failed to execute early startup for monitor.ui

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#130]
I installed CodingSpectator v1.0.0.201101151513 on a fresh instance of Eclipse Helios SR1. I found the following item in the error log the first time I launched Eclipse.

<pre>
java.lang.ExceptionInInitializerError
    at edu.illinois.codingspectator.monitor.ui.Activator.earlyStartup(Activator.java:65)
    at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:87)
    at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:66)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.Workbench$59.run(Workbench.java:2409)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
    at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:121)
    at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:606)
    at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:601)
    at org.eclipse.core.runtime.Platform.getStateLocation(Platform.java:1009)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.<clinit>(Submitter.java:41)
    ... 6 more
</pre>

It looks like that `org.eclipse.core.runtime.Platform.getStateLocation` causes an NPE.

**Comment by vazexqi** [comment]
This could be related to #131 where it was not installed cleanly and thus there is not proper state location.

Incidentally, I did not get this on the first launch. The CodingSpectator dialog box popped-up properly for me and I could cancel it.

**Comment by reprogrammer** [comment]
I close this issue as it hasn't occurred again.
