### ISSUE TITLE
Unable to execute early startup code for an extension

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#148]
When I launched my instance of Eclipse (from eb25f7f4b0874337a596a5f7726578cf52eceaaf), I get the following exception:

<pre>
!ENTRY org.eclipse.epp.usagedata.recording 4 0 2011-02-04 17:01:33.445
!MESSAGE Unable to execute early startup code for an extension
!STACK 0
java.lang.AbstractMethodError: org.eclipse.epp.usagedata.internal.ui.uploaders.AskUserUploader.startTransferToCodingSpectator()V
    at org.eclipse.epp.usagedata.internal.recording.uploading.UploadManager.startTransferToCodingSpectator(UploadManager.java:226)
    at org.eclipse.epp.usagedata.internal.recording.Startup.earlyStartup(Startup.java:26)
    at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:87)
    at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:66)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.Workbench$58.run(Workbench.java:2398)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by vazexqi** [comment]
This might be related to issue #127

**Comment by vazexqi** [comment]
This was a mistake on my part. I had the `org.eclipse.epp.usagedata.ui` package closed in my workspace which was why it was not able to instantiate the AskUserUploader class.
