### ISSUE TITLE
All of the control buttons of CodingTracker become disabled

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#177]
While replaying the change sequence from "P1/04cba2b6-8892-4008-8526-19026df460c1/1.0.0.201011031917/codingtracker/codechanges.txt" all the buttons became disabled suddenly. See [the screen shot showing that all buttons of CodingTracker became disabled](http://s1.postimage.org/em9a30y4s/Coding_Tracker_Control_Buttons_Are_Disabled.png).

I also got the following exceptions in the console.

<pre>
!ENTRY org.eclipse.ui 4 0 2011-03-17 12:37:38.709
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.RuntimeException: java.lang.RuntimeException: Replaced text is not present in the document: Replaced text: sizeOfChess
New text: m
Offset: 775
Length: 11
Timestamp: 1289361089653)
    at org.eclipse.swt.SWT.error(SWT.java:4083)
    at org.eclipse.swt.SWT.error(SWT.java:3998)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:137)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3515)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3164)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Replaced text is not present in the document: Replaced text: sizeOfChess
New text: m
Offset: 775
Length: 11
Timestamp: 1289361089653
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer.replayAndAdvanceCurrentUserOperation(UserOperationReplayer.java:240)
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer.access$3(UserOperationReplayer.java:225)
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer$UserOperationExecutionThread$1.run(UserOperationReplayer.java:324)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
    ... 23 more
Caused by: java.lang.RuntimeException: Replaced text is not present in the document: Replaced text: sizeOfChess
New text: m
Offset: 775
Length: 11
Timestamp: 1289361089653
    at edu.illinois.codingspectator.codingtracker.operations.textchanges.TextChangeOperation.replay(TextChangeOperation.java:74)
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer.replayAndAdvanceCurrentUserOperation(UserOperationReplayer.java:237)
    ... 27 more
</pre>

**Comment by reprogrammer** [comment]
The next time I replayed the same change sequence, I got the following similar exception later, and all the buttons became disabled when I clicked on the only enabled button ("Fast").

<pre>
!ENTRY org.eclipse.ui 4 0 2011-03-17 13:17:31.216
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.RuntimeException: java.lang.RuntimeException: Replaced text is not present in the document: Replaced text: #
New text: 
Offset: 7078
Length: 1
Timestamp: 1289461182393)
    at org.eclipse.swt.SWT.error(SWT.java:4083)
    at org.eclipse.swt.SWT.error(SWT.java:3998)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:137)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3515)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3164)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Replaced text is not present in the document: Replaced text: #
New text: 
Offset: 7078
Length: 1
Timestamp: 1289461182393
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer.replayAndAdvanceCurrentUserOperation(UserOperationReplayer.java:240)
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer.access$3(UserOperationReplayer.java:225)
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer$UserOperationExecutionThread$1.run(UserOperationReplayer.java:324)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
    ... 23 more
Caused by: java.lang.RuntimeException: Replaced text is not present in the document: Replaced text: #
New text: 
Offset: 7078
Length: 1
Timestamp: 1289461182393
    at edu.illinois.codingspectator.codingtracker.operations.textchanges.TextChangeOperation.replay(TextChangeOperation.java:74)
    at edu.illinois.codingspectator.codingtracker.replaying.UserOperationReplayer.replayAndAdvanceCurrentUserOperation(UserOperationReplayer.java:237)
    ... 27 more
</pre>

**Comment by Wanderer777** [comment]
The user is explicitly notified of any replay exception in a message box, after which the control buttons are restored. Addressed in 4b2e3ad1a8e203ca49d65627f9ef6dbb2978508b

**Comment by Wanderer777** [comment]
Replaying the above operation sequence revealed that the following additional problems should be addressed:
1. CodingTracker should handle appropriately different encodings while recording/replaying. The already produced operation sequence has to be pre-processed to get fixed (it contains unrecognized symbols that are represented by 2 (and in sometimes by 4) characters, which affectes offsets and prevents correct replay). This is fixed in 4a9733488c9bad2335e1167ca514e1bcb8a7482c
2. CodingTracker should implement replay for user operations involving conflict editors (such operations are present in the above operation sequence). This is fixed in 7052e0729d56fda3c35bd338c328331c5222b64c

**Comment by reprogrammer** [comment]
I'd like to skip the first part of the change sequence and replay the changes that come after the exceptions reported above. I believe I can only begin the replay from a snapshot operation, right? I plan to find the first snapshot after the above exceptions as follows. Let _te_ be the timestamp at which the replayer throws the exception. I'll open the change sequence in the replayer and look for the timestamp _te_. Then, I'll locate the first snapshot operation after _te_. Let _ts_ be the timestamp of this snapshot operation.  I'll open the change sequence in a text editor, find the timestamp _ts_ and deleted the first part of the file until the operation recorded at _ts_. Please let me know if you know of a better way to resume the replay after an exception.

**Comment by Wanderer777** [comment]
The tricky part is that there are multiple files and each could be snapshoted at different time. So, if you remove everything preceding a snapshot of one file, operations that affect other files would fail, unless they are preceded by their corresponding snapshots as well. So, essencially what you like to do in the above scenario is to remove operations that precede _ts_ and affect the file snapshoted at the timestamp _ts_ (and keep all other preceding operations). As you can imagine, this is a very labor-intensive task. 

An easier way is to just ignore exceptions, i.e. continue execution of the operation sequence regardless of the thrown exceptions and eventually you'll reach a snapshot (if it exists), after which the execution would become normal. So, I suggest the following approach: after you encounter an exception, look for the nearest following snapshot of the file, for which the exception was thrown, put a breakpoint there, comment out re-throwing replay exceptions (that would basically mean that the replayer would procede to the follwoing operation even if the current operation failed), execute operation sequence till your breakpoint, restore re-throwing of replay exceptions, and continue normal replay. Although there are several steps in this approach, it is almost completely automated (no need to manually change the operations record), so it should not take much time. Nevertheless, I would suggest trying to replay operation sequences of other participants first, before you start overcoming exceptions (and hopefully, by that time I would fix either recorder/replayer or the recorded sequences such that no exceptions are thrown).

**Comment by Wanderer777** [comment]
The sequence is fixed, all discovered issues are fixed.
