### ISSUE TITLE
CodingSpectator failed to copy Eclipse LTK data

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#187]
I noticed the following error in the error log of my Eclipse Helios SR2. This issue is related to issue #167.

<pre>
eclipse.buildId=M20110210-1200
java.version=1.6.0_24
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product

Error
Mon Mar 28 16:20:45 CDT 2011
Could not write file: /home/workspace/keshmesh/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.201103211747/eclipse-refactorings/edu.illinois.keshmesh.transformer.core/.svn/all-wcprops.

java.io.FileNotFoundException: /home/workspace/keshmesh/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.201103211747/eclipse-refactorings/edu.illinois.keshmesh.transformer.core/.svn/all-wcprops (Permission denied)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:179)
at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:382)
at org.eclipse.core.filesystem.provider.FileStore.copyFile(FileStore.java:218)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:140)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.transferEclipseRefactoringHistory(EclipseRefactoringHistoryCapturer.java:38)
at edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.postSubmit(EclipseRefactoringHistoryCapturer.java:52)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.notifyPostSubmit(Submitter.java:133)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:103)
at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by reprogrammer** [comment]
This issue affects users like me who open a workspace with meta data from an old version of CodingSpectator inside a new version of CodingSpectator that stores the Subversion working copy at `edu.illinois.codingspectator.data`. If the user is upgrading from a version of CodingSpectator that is not newer than v1.0.0.201102192319, he/she has to install the new version on a clean workspace and cannot reuse old workspaces.
