### ISSUE TITLE
Some of the UI tests fail when run with other tests

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#201]
When I run all of the tests for the move refactorings at once, T22, T21 and T23 fail. But, when I run these tests individually they pass.

I used the following test suite to debug the problem.

```
package edu.illinois.codingspectator.ui.tests.move;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses({ T18.class, T22.class, T20.class, T21.class, T26.class, T23.class })
public class ProblematicTests {

}
```

move.T23 in the above test suite fails with the following stack trace.

<pre>
org.junit.ComparisonFailure: expected:<...is.codingspectator.D['
- Original project: 'Prj'
- Destination element: 'edu.illinois.codingspectator.D]'
- Original element...> but was:<...is.codingspectator.D[estinationFile.java'
- Original project: 'Prj'
- Destination element: 'edu.illinois.codingspectator.DestinationFile.java]'
- Original element...>
    at org.junit.Assert.assertEquals(Assert.java:123)
    at org.junit.Assert.assertEquals(Assert.java:145)
    at edu.illinois.codingspectator.ui.tests.DescriptorComparator.assertMatches(DescriptorComparator.java:26)
    at edu.illinois.codingspectator.ui.tests.RefactoringLogChecker.assertMatch(RefactoringLogChecker.java:35)
    at edu.illinois.codingspectator.ui.tests.RefactoringTest.doRefactoringShouldBeLogged(RefactoringTest.java:86)
    at edu.illinois.codingspectator.ui.tests.RefactoringTest.refactoringShouldBeLogged(RefactoringTest.java:125)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.swtbot.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:64)
    at org.eclipse.swtbot.eclipse.core.UITestApplication.runTests(UITestApplication.java:117)
    at org.eclipse.ui.internal.testing.WorkbenchTestable$1.run(WorkbenchTestable.java:71)
    at java.lang.Thread.run(Thread.java:662)
</pre>

Because `DestinationFile.java` is used in the previous test (T26) and not T23, I suspect that some state from previous tests leaks into the following tests.

**Comment by reprogrammer** [comment]
I can no longer reproduce this problem. So, I'm closing this issue.
