### ISSUE TITLE
CodingSpectator throws StringIndexOutOfBoundsException on rename refactoring

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#220]
I got the following exception when trying to rename a constant in linked mode editing.

<pre>
java.lang.reflect.InvocationTargetException
at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:421)
at org.eclipse.jface.window.ApplicationWindow$1.run(ApplicationWindow.java:759)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
at org.eclipse.jface.window.ApplicationWindow.run(ApplicationWindow.java:756)
at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2606)
at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:217)
at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:175)
at org.eclipse.jdt.ui.refactoring.RenameSupport.perform(RenameSupport.java:198)
at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.doRename(RenameLinkedMode.java:382)
at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode$EditorSynchronizer.left(RenameLinkedMode.java:124)
at org.eclipse.jface.text.link.LinkedModeModel.exit(LinkedModeModel.java:341)
at org.eclipse.jface.text.link.LinkedModeUI$4.run(LinkedModeUI.java:1194)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3515)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3164)
at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 6236
at java.lang.String.substring(String.java:1934)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.CodeSnippetInformationExtractor.getText(CodeSnippetInformationExtractor.java:42)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.TextSelectionCodeSnippetInformationExtractor.getSelectedText(TextSelectionCodeSnippetInformationExtractor.java:43)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.TextSelectionCodeSnippetInformationExtractor.extractCodeSnippetInformation(TextSelectionCodeSnippetInformationExtractor.java:37)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.CodeSnippetInformationFactory.extractCodeSnippetInformation(CodeSnippetInformationFactory.java:41)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.CodeSnippetInformationFactory.extractCodeSnippetInformation(CodeSnippetInformationFactory.java:45)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedProcessorDelegate.getCodeSnippetInformation(WatchedProcessorDelegate.java:65)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedProcessorDelegate.populateInstrumentationData(WatchedProcessorDelegate.java:39)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedRenameProcessorDelegate.getSimpleRefactoringDescriptor(WatchedRenameProcessorDelegate.java:27)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedJavaRenameProcessor.getSimpleRefactoringDescriptor(WatchedJavaRenameProcessor.java:13)
at org.eclipse.ltk.core.refactoring.participants.RenameRefactoring.getSimpleRefactoringDescriptor(RenameRefactoring.java:62)
at org.eclipse.ltk.core.refactoring.codingspectator.Logger.createRefactoringDescriptor(Logger.java:45)
at org.eclipse.ltk.core.refactoring.codingspectator.Logger.logRefactoringEvent(Logger.java:83)
at org.eclipse.ltk.core.refactoring.codingspectator.Logger.logRefactoringEvent(Logger.java:78)
at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.logRefactoring(RefactoringExecutionHelper.java:142)
at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper$Operation.run(RefactoringExecutionHelper.java:111)
at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:40)
at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:806)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1970)
at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5865)
at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:106)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Root exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: 6236
at java.lang.String.substring(String.java:1934)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.CodeSnippetInformationExtractor.getText(CodeSnippetInformationExtractor.java:42)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.TextSelectionCodeSnippetInformationExtractor.getSelectedText(TextSelectionCodeSnippetInformationExtractor.java:43)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.TextSelectionCodeSnippetInformationExtractor.extractCodeSnippetInformation(TextSelectionCodeSnippetInformationExtractor.java:37)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.CodeSnippetInformationFactory.extractCodeSnippetInformation(CodeSnippetInformationFactory.java:41)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.CodeSnippetInformationFactory.extractCodeSnippetInformation(CodeSnippetInformationFactory.java:45)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedProcessorDelegate.getCodeSnippetInformation(WatchedProcessorDelegate.java:65)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedProcessorDelegate.populateInstrumentationData(WatchedProcessorDelegate.java:39)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedRenameProcessorDelegate.getSimpleRefactoringDescriptor(WatchedRenameProcessorDelegate.java:27)
at org.eclipse.jdt.internal.corext.refactoring.codingspectator.WatchedJavaRenameProcessor.getSimpleRefactoringDescriptor(WatchedJavaRenameProcessor.java:13)
at org.eclipse.ltk.core.refactoring.participants.RenameRefactoring.getSimpleRefactoringDescriptor(RenameRefactoring.java:62)
at org.eclipse.ltk.core.refactoring.codingspectator.Logger.createRefactoringDescriptor(Logger.java:45)
at org.eclipse.ltk.core.refactoring.codingspectator.Logger.logRefactoringEvent(Logger.java:83)
at org.eclipse.ltk.core.refactoring.codingspectator.Logger.logRefactoringEvent(Logger.java:78)
at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.logRefactoring(RefactoringExecutionHelper.java:142)
at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper$Operation.run(RefactoringExecutionHelper.java:111)
at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:40)
at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:806)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1970)
at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5865)
at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:106)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
</pre>

**Comment by reprogrammer** [comment]
I noticed that CodingSpectator threw this exception when I was trying to rename the constant from one of its uses out of the file in which the constant was declared. When I tried to rename the constant from where it was declared, I didn't get the exception. I don't know if the exception depends on where the user invokes the refactoring. But, I document my observation in case it provides some hints on how to reproduce and debug this problem.

To reproduce this problem the offset at which the use of the constant is found at should be greater than the size of the file that contains the definition of the constant.
