### ISSUE TITLE
FileNotFoundException while transferring Eclipse LTK data

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#256]
I found the following in my error log.

<pre>
eclipse.buildId=M20110210-1200
java.version=1.6.0_24
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product

Warning
Mon Jun 27 15:50:48 CDT 2011
Failed to transfer Eclipse LTK data to CodingSpectator...

org.eclipse.core.runtime.CoreException: Could not write file: /home/user/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.201105300951/eclipse-refactorings/edu.illinois.dpjizer.region.core/.svn/all-wcprops.
at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:55)
at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:391)
at org.eclipse.core.filesystem.provider.FileStore.copyFile(FileStore.java:218)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:140)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.transferEclipseRefactoringHistory(EclipseRefactoringHistoryCapturer.java:38)
at edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.postSubmit(EclipseRefactoringHistoryCapturer.java:52)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.notifyPostSubmit(Submitter.java:133)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:103)
at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.FileNotFoundException: /home/user/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.201105300951/eclipse-refactorings/edu.illinois.dpjizer.region.core/.svn/all-wcprops (Permission denied)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:179)
at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:382)
... 18 more
</pre>

<pre>
eclipse.buildId=M20110210-1200
java.version=1.6.0_24
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.rcp.product

Error
Mon Jun 27 15:50:48 CDT 2011
Could not write file: /home/user/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.201105300951/eclipse-refactorings/edu.illinois.dpjizer.region.core/.svn/all-wcprops.

java.io.FileNotFoundException: /home/user/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.201105300951/eclipse-refactorings/edu.illinois.dpjizer.region.core/.svn/all-wcprops (Permission denied)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:179)
at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:382)
at org.eclipse.core.filesystem.provider.FileStore.copyFile(FileStore.java:218)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:140)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at org.eclipse.core.filesystem.provider.FileStore.copyDirectory(FileStore.java:178)
at org.eclipse.core.filesystem.provider.FileStore.copy(FileStore.java:138)
at org.eclipse.core.internal.filesystem.local.LocalFile.copy(LocalFile.java:111)
at edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.transferEclipseRefactoringHistory(EclipseRefactoringHistoryCapturer.java:38)
at edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.postSubmit(EclipseRefactoringHistoryCapturer.java:52)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.notifyPostSubmit(Submitter.java:133)
at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:103)
at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by reprogrammer** [comment]
Before v1.0.0.201103210128, `.metadata/.plugins/org.eclipse.ltk.core.refactoring` used to be an SVN working copy. But, issue #167 moved the working copy to `.metadata/.plugins/edu.illinois.codingspectator.data`. When I upgraded CodingSpectator, `.metadata/.plugins/org.eclipse.ltk.core.refactoring` still contained some SVN meta data files. And, as a result of issue #167, CodingSpectator tries to copy Eclipse log files from `.metadata/.plugins/org.eclipse.ltk.core.refactoring` to the new watched directory at `.metadata/.plugins/edu.illinois.codingspectator.data` after every submission. However, both directories contain some read only SVN meta data files and the copy operation tries to overwrite the read only meta data file in `.metadata/.plugins/edu.illinois.codingspectator.data`.

I fixed this issue in my workspace by deleting all SVN meta data files in `.metadata/.plugins/org.eclipse.ltk.core.refactoring` and `.metadata/.plugins/edu.illinois.codingspectator.data`.

Fortunately, this issue doesn't affect any of our current participants because none of them has ever used a version of CodingSpectator as old as v1.0.0.201103210128.
