### ISSUE TITLE
BundleUpdater threw an NPE

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#284]
I got the following exception when pushed the "Upload Now" button on the preference page.

<pre>
eclipse.buildId=unknown
java.version=1.6.0_26
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -product org.eclipse.epp.package.rcp.product -data ../CodingSpectatorRuntime -dev file:.metadata/.plugins/org.eclipse.pde.core/CodingSpectator/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

Error
Sat Jul 16 22:32:07 CDT 2011
Problems occurred when invoking code from plug-in: "edu.illinois.codingspectator.monitor.ui".

java.lang.NullPointerException
    at edu.illinois.bundleupdater.BundleUpdater.checkForUpdates(BundleUpdater.java:80)
    at edu.illinois.codingspectator.monitor.ui.updates.Updater.postSubmit(Updater.java:33)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter$3.run(Submitter.java:167)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.notifyPostSubmit(Submitter.java:163)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:109)
    at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by reprogrammer** [comment]
`BundleUpdater` threw an NPE because no profile is available in the development mode of Eclipse. Commit beb137fe09e4a6fb4d0d8601a8c6cb04b0838909 reports NPE's of `BundleUpdater` to the error log. I tested the new `BundleUpdater` on Helios and Indigo and made sure that it worked.
