### ISSUE TITLE
edu.illinois.codingspectator.csvtosql either hangs or throws an exception

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#290]
The `edu.illinois.codingspectator.csvtosql` application either hangs while shutting down the database or throws the following exception.

<pre>
2011-08-04T07:52:29.024-0500  WARNING  ScriptWriter synch error:
java.io.SyncFailedException: sync failed
        at java.io.FileDescriptor.sync(Native Method)
        at org.hsqldb.lib.FileUtil$FileSync.sync(Unknown Source)
        at org.hsqldb.scriptio.ScriptWriterBase.forceSync(Unknown Source)
        at org.hsqldb.persist.Log.synchLog(Unknown Source)
        at org.hsqldb.persist.Log.checkpointClose(Unknown Source)
        at org.hsqldb.persist.Log.checkpoint(Unknown Source)
        at org.hsqldb.persist.Log.checkpoint(Unknown Source)
        at org.hsqldb.persist.Logger.checkpoint(Unknown Source)
        at org.hsqldb.StatementCommand.getResult(Unknown Source)
        at org.hsqldb.StatementCommand.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Database$CheckpointRunner.run(Unknown Source)
        at org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:619)
</pre>

This problem sometimes leads to a corrupt database and sometimes  does not.

The first time I noticed this problem was after commit 8162990728fd5d18ad2f98be3e3dbd55635ac8d5. But, I didn't find any problem in this commit. We should try running the application on the previous commit to see if this commit has introduced the bug.

**Comment by reprogrammer** [comment]
The `edu.illinois.codingspectator.csvtosql` application hung even after commit 17c9d8edfc372b0cf8196be98f91fcd93651875b.
