### ISSUE TITLE
Reverting the watched folder to a version that lacks some committed files is problematic

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#309]
CodingSpectator updates the working copy and resolves the conflicts that may arise. However, these step don't seem to be sufficient to avoid the following exception:

<pre>
eclipse.buildId=unknown
java.version=1.6.0_26
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.rcp.product
Command-line arguments:  -product org.eclipse.epp.package.rcp.product -data /path/to/workspace/../CodingSpectatorRuntime -dev file:/path/to/workspace/.metadata/.plugins/org.eclipse.pde.core/CodingSpectator/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

Error
Mon Aug 15 01:03:43 CDT 2011
Failed to upload CodingSpectator data.

edu.illinois.codingspectator.monitor.ui.submission.Submitter$SubmissionException: org.tmatesoft.svn.core.SVNException: svn: Directory '/path/to/workspace/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/performed/Prj' is missing
svn: Directory '/path/to/workspace/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/performed/Prj' is missing
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:106)
    at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.tmatesoft.svn.core.SVNException: svn: Directory '/path/to/workspace/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/performed/Prj' is missing
svn: Directory '/path/to/workspace/.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/performed/Prj' is missing
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
    at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:623)
    at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:274)
    at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:262)
    at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.doReport(DAVConnection.java:266)
    at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.runReport(DAVRepository.java:1261)
    at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.update(DAVRepository.java:818)
    at org.tmatesoft.svn.core.wc.SVNUpdateClient.update(SVNUpdateClient.java:564)
    at org.tmatesoft.svn.core.wc.SVNUpdateClient.doCheckout(SVNUpdateClient.java:930)
    at edu.illinois.codingspectator.monitor.core.submission.RemoteSVNManager.doCheckout(RemoteSVNManager.java:54)
    at edu.illinois.codingspectator.monitor.core.submission.SVNManager.doCheckout(SVNManager.java:33)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:100)
    ... 2 more
</pre>

I reverted the watched folder to a revision that lacked the `Prj` folder. Since the `Prj` had been already committed to the latest revision of the watched folder, it caused the above exception. I don't quite know why the SVN update and resolve commands didn't take care of this problem.

**Comment by reprogrammer** [comment]
To understand why the SVN update and resolve operations do not resolve the above conflict, I performed these operations using the SVN command line client manually.

<pre>
$ svn up .metadata/.plugins/edu.illinois.codingspectator.data/
Skipped '.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier'
At revision 417.
Summary of conflicts:
  Skipped paths: 1
$ svn st .metadata/.plugins/edu.illinois.codingspectator.data/
A  +  C .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier
      >   local edit, incoming delete upon update
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/codingtracker/codechanges.txt
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/performed/P/2011/8/34/refactorings.history
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/performed/P/2011/8/34/refactorings.index
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/refactorings/refactoring-problems.log
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/eclipse-refactorings/P/2011/8/34/refactorings.history
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/eclipse-refactorings/P/2011/8/34/refactorings.index
M  +    .metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier/error.log
$ svn resolve .metadata/.plugins/edu.illinois.codingspectator.data/ -R --accept=theirs-full
svn: warning: Tree conflicts can only be resolved to 'working' state; '.metadata/.plugins/edu.illinois.codingspectator.data/1.0.0.qualifier' not resolved
</pre>

**Comment by reprogrammer** [comment]
It looks like the only way to resolve a tree conflict such as the above one is to run the following command:

```
$ svn resolve .metadata/.plugins/edu.illinois.codingspectator.data/ -R --accept=working
```

**Comment by reprogrammer** [comment]
See http://svnbook.red-bean.com/en/1.6/svn.tour.treeconflicts.html to learn more about tree conflicts in SVN.

**Comment by reprogrammer** [comment]
I used the "working" strategy to resolve the tree conflict as described in my previous [comment](https://github.com/vazexqi/CodingSpectator/issues/309#issuecomment-1805319). However, I got the following exception when I tried to upload the CodingSpectator's data manually.

<pre>
eclipse.buildId=I20110613-1736
java.version=1.6.0_26
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /path/to/workspace -dev file:/path/to/dev/workspace/.metadata/.plugins/org.eclipse.pde.core/CodingSpectator/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

Error
Mon Aug 15 02:24:08 CDT 2011
Failed to upload CodingSpectator data.

edu.illinois.codingspectator.monitor.ui.submission.Submitter$SubmissionException: org.tmatesoft.svn.core.SVNException: svn: Commit failed (details follow):
svn: File '/svn/ganje/nchen/00000000-0000-0000-0000-000000000000/1.0.0.qualifier/codingtracker/codechanges.txt' already exists
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:102)
    at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.tmatesoft.svn.core.SVNException: svn: Commit failed (details follow):
svn: File '/svn/ganje/nchen/00000000-0000-0000-0000-000000000000/1.0.0.qualifier/codingtracker/codechanges.txt' already exists
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
    at org.tmatesoft.svn.core.wc.SVNCommitClient.doCommit(SVNCommitClient.java:899)
    at org.tmatesoft.svn.core.wc.SVNCommitClient.doCommit(SVNCommitClient.java:828)
    at edu.illinois.codingspectator.monitor.core.submission.RemoteSVNManager.doCommit(RemoteSVNManager.java:60)
    at edu.illinois.codingspectator.monitor.core.submission.SVNManager.doCommit(SVNManager.java:37)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:99)
    ... 2 more
</pre>


I found a related [post on stackoverflow](http://stackoverflow.com/q/1407973).

**Comment by reprogrammer** [comment]
I couldn't reproduce [the above problem](https://github.com/vazexqi/CodingSpectator/issues/309#issuecomment-1805357) by executing a sequence of the commands of an SVN command line client.
