### ISSUE TITLE
Submitter fails while notifying listeners about preCommit

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#326]
Submitter throws the following exception while notifying its listeners.

<pre>
!ENTRY edu.illinois.codingspectator.monitor.ui 4 2 2011-10-10 13:12:47.118
!MESSAGE Problems occurred when invoking code from plug-in: "edu.illinois.codingspectator.monitor.ui".
!STACK 0
java.lang.AbstractMethodError: edu.illinois.codingspectator.eclipserefactorings.capturing.EclipseRefactoringHistoryCapturer.preCommit()V
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter$2.run(Submitter.java:166)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.notifyPreCommit(Submitter.java:162)
    at edu.illinois.codingspectator.monitor.ui.submission.Submitter.submit(Submitter.java:99)
    at edu.illinois.codingspectator.monitor.ui.Uploader$1.run(Uploader.java:56)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by reprogrammer** [comment]
The problem persists even when we close the Eclipse project `edu.illinois.codingspectator.refactorings.capturing`. This shows that Eclipse is using old version of this bundle that does not implement `preCommit`.

**Comment by reprogrammer** [comment]
I didn't encounter this exception when I used a fresh instance of Eclipse without CodingSpectator.
