### ISSUE TITLE
Signed Jar file error on svnkit plug-in

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#39]
Here is the error that we get:

<pre>
An error occurred while collecting items to be installed
session context was:(profile=epp.package.rcp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,org.tmatesoft.svn_1.3.4.eclipse,1.0.0.
Error reading signed content:/var/folders/DF/DFH4kIjaFAyM1zkj+iHmyU+++TI/-Tmp-/signatureFile4035969860381721975.jar
An error occurred while processing the signatures for the file: /var/folders/DF/DFH4kIjaFAyM1zkj+iHmyU+++TI/-Tmp-/signatureFile4035969860381721975.jar
</pre>

**Comment by vazexqi** [comment]
When we looked at the error log of Eclipse here are other pieces of information that we gather:

<pre>
java.security.SignatureException: Either the manifest file or the signature file has been tampered in this jar: /var/folders/DF/DFH4kIjaFAyM1zkj+iHmyU+++TI/-Tmp-/signatureFile4035969860381721975.jar
at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.verifyManifestAndSignatureFile(SignatureBlockProcessor.java:154)
at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.processSigner(SignatureBlockProcessor.java:104)
at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.process(SignatureBlockProcessor.java:60)
at org.eclipse.osgi.internal.signedcontent.SignedBundleFile.setBundleFile(SignedBundleFile.java:47)
at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:247)
at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verifyContent(SignatureVerifier.java:77)
at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verify(SignatureVerifier.java:59)
at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.close(SignatureVerifier.java:100)
at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.reportStatus(SimpleArtifactRepository.java:906)
at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:510)
at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:576)
at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.getArtifact(MirrorRequest.java:248)
at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transferSingle(MirrorRequest.java:223)
at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transfer(MirrorRequest.java:179)
at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.perform(MirrorRequest.java:115)
at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:565)
at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifacts(SimpleArtifactRepository.java:616)
at org.eclipse.equinox.internal.p2.engine.DownloadManager.fetch(DownloadManager.java:88)
at org.eclipse.equinox.internal.p2.engine.DownloadManager.start(DownloadManager.java:77)
at org.eclipse.equinox.internal.p2.engine.phases.Collect.completePhase(Collect.java:76)
at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:216)
at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:84)
at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:44)
at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:73)
at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:44)
at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:174)
at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:79)
at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:177)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

**Comment by vazexqi** [comment]
We created a new plug-in from Jar archive for SVNKit. This time we did _not_ expand the jar files when using the "Plug-in from Existing Jar Archives".By not expanding the jar file we prevented the SignatureException since we did not tamper with the contents of the JAR file and thus did not invalidate the DSA.
