### ISSUE TITLE
The monitor.tests plugin doesn't load the monitor plugin.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#52]
Even though both `edu.illinois.refactoringwatcher.monitor` and `edu.illinois.refactoringwatcher.monitor.tests` are set up to start lazily whenever one of their classes is accessed, `edu.illinois.refactoringwatcher.monitor.tests` fails to access the preference store of `edu.illinois.refactoringwatcher.monitor` just because `Activator.getDefault()` returns `null`.

<pre>
java.lang.NullPointerException
    at edu.illinois.refactoringwatcher.monitor.prefs.PrefsFacade.getPreferenceStore(PrefsFacade.java:17)
    at edu.illinois.refactoringwatcher.monitor.prefs.PrefsFacade.setPreferenceValue(PrefsFacade.java:25)
    at edu.illinois.refactoringwatcher.monitor.prefs.PrefsFacade.setUUID(PrefsFacade.java:39)
    at edu.illinois.refactoringwatcher.monitor.tests.TestSubmitter.setUpBeforeClass(TestSubmitter.java:71)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

java.lang.NullPointerException
    at edu.illinois.refactoringwatcher.monitor.tests.TestSubmitter.tearDownAfterClass(TestSubmitter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
</pre>

**Comment by vazexqi** [comment]
Is this related to #51? Or is this because of a different problem all together?

**Comment by reprogrammer** [comment]
It's a totally different problem for making all the methods of `PrefsFacade` `synchronized` didn't fix it.

**Comment by vazexqi** [comment]
I cannot reproduce this problem on my machine. However, I think I was able to solve #51. See my comments there.

**Comment by reprogrammer** [comment]
I was running the test plugin as a JUnit test not a JUnit Test Plugin. So, this issue doesn't need any fix.
