### ISSUE TITLE
When CodingTracker tries to log its events, the directory structure may have not been created

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#68]
When running CodingTracker on a clean workspace that doesn't have the watched directory, we get the following exception.

<pre>
java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:883)
    at edu.illinois.codingspectator.codingtracker.Logger.<init>(Logger.java:64)
    at edu.illinois.codingspectator.codingtracker.CodeChangeTracker.<init>(CodeChangeTracker.java:48)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:904)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.ui.internal.WorkbenchPlugin$1.run(WorkbenchPlugin.java:267)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:52)
    at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:263)
    at org.eclipse.ui.internal.EarlyStartupRunnable.getExecutableExtension(EarlyStartupRunnable.java:117)
    at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:66)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.Workbench$59.run(Workbench.java:2409)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
</pre>

If you use EFS, it will create the necessary directories for you. Please see the following method from `org.eclipse.ltk.internal.core.refactoring.history.RefactoringHistorySerializer.getFileStore(String)`.

<pre>
private IFileStore getFileStore(String historyFolder) {
        String directorySeparator= "/"; //$NON-NLS-1$
        String[] directories= historyFolder.split(directorySeparator);
        IFileStore store= EFS.getLocalFileSystem().getStore(RefactoringCorePlugin.getDefault().getStateLocation()).getChild(directories[0]);
        for (int i= 1; i < directories.length; i++)
            store= store.getChild(directories[i]);
        return store;
    }
</pre>

**Comment by vazexqi** [comment]
I just realized that the code above can be simplified to 

<pre>
    private IFileStore getFileStore(String historyFolder) {
        return EFS.getLocalFileSystem().getStore(RefactoringCorePlugin.getDefault().getStateLocation()).getChild(historyFolder);
    }
</pre>

because getChild will automatically do the recursive calls for you.

**Comment by Wanderer777** [comment]
I implemented an even simpler solution:
    file.getParentFile().mkdirs();
