### ISSUE TITLE
Cannot test i.e. Run as Eclipse Application from Windows

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#69]
How to reproduce:
1. Check out the project and all prerequisites into a workspace. You may close the test projects if you wish.
2. Build.
3. Select one of the plug-in projects and launch as "Eclipse Application". This will also launch all the other plug-ins in the workspace.
4. The new test/debug Eclipse Application will appear. Create a new Java Project and create a HelloWorld.java file in it that only outputs  "Hello World!"
5. Try to do either of the following:
6. Try to refactor something in the code e.g. Extract Method for System.out.println("Hello World!");
7. Try to run HelloWorld.java as a Java application
8. The test/debug Eclipse Application will error out with a PermGen exception.  This exception seems to happen even if I increase the heap size to 1024M.

I am running Windows 7 64-bit with the latest version of the Sun JVM.

**Comment by Wanderer777** [comment]
I tried both scenarios (i.e. Extract Method and running as a Java application). I could not reproduce this problem: both fine grained code changes and your refactoring capturings are saved ok to the corresponding files. I am running it on Windows XP SP2 32-bit with JDK1.6.0_16.

**Comment by vazexqi** [comment]
OK. I can show this problem to you on Monday. It's affecting both my office machine and my own machine (MacBook Pro running Windows 7 64-bit using Boot Camp)

**Comment by Wanderer777** [comment]
I encountered this problem after I started to use SVN in the launched Eclipse application. I can use SVN for a while, but then I have this problem, in particular when I handle commit conflicts.

**Comment by vazexqi** [comment]
Here is the log file from my machine:

<pre>

!SESSION 2010-10-08 16:37:24.673 -----------------------------------------------
eclipse.buildId=M20100909-0800
java.version=1.6.0_17
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\nchen\Git\CodingSpectator/../runtime-EclipseApplication -dev file:C:/Users/nchen/Git/CodingSpectator/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.ui 4 4 2010-10-08 16:37:52.593
!MESSAGE Referenced part does not exist yet: org.eclipse.ui.views.TaskList.

!ENTRY org.eclipse.ui 4 0 2010-10-08 16:38:29.904
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassLoader(ClasspathManager.java:469)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:449)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClassInternal(Unknown Source)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassLoader(ClasspathManager.java:469)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:449)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClassInternal(Unknown Source)

!ENTRY org.eclipse.ui 4 0 2010-10-08 16:38:30.531
!MESSAGE Error occurred during status handling
!STACK 0
java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:580)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:550)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:481)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass_LockClassLoader(ClasspathManager.java:469)
    at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:449)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
    at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClassInternal(Unknown Source)
    at org.eclipse.ui.internal.statushandlers.WorkbenchStatusDialogManagerImpl.doAddStatusAdapter(WorkbenchStatusDialogManagerImpl.java:259)
    at org.eclipse.ui.internal.statushandlers.WorkbenchStatusDialogManagerImpl.addStatusAdapter(WorkbenchStatusDialogManagerImpl.java:197)
    at org.eclipse.ui.statushandlers.WorkbenchStatusDialogManager.addStatusAdapter(WorkbenchStatusDialogManager.java:156)
    at org.eclipse.ui.statushandlers.WorkbenchErrorHandler.showStatusAdapter(WorkbenchErrorHandler.java:101)
    at org.eclipse.ui.statushandlers.WorkbenchErrorHandler.handle(WorkbenchErrorHandler.java:57)
    at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handle(IDEWorkbenchErrorHandler.java:106)
    at org.eclipse.ui.internal.WorkbenchErrorHandlerProxy.handle(WorkbenchErrorHandlerProxy.java:36)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:189)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:231)
    at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:242)
    at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopException(WorkbenchAdvisor.java:326)
    at org.eclipse.ui.internal.ExceptionHandler.handleException(ExceptionHandler.java:65)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:829)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation$1.run(RefactoringWizardOpenOperation.java:180)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)

!ENTRY org.eclipse.core.jobs 4 2 2010-10-08 16:39:14.362
!MESSAGE An internal error occurred during: "Task List Save Job".

!ENTRY org.eclipse.ui 4 0 2010-10-08 16:39:15.008
!MESSAGE Unhandled event loop exception

!ENTRY org.eclipse.ui 4 0 2010-10-08 16:39:16.336
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: PermGen space)
    at org.eclipse.swt.SWT.error(SWT.java:4083)
    at org.eclipse.swt.SWT.error(SWT.java:3998)
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
    at null
Caused by: java.lang.OutOfMemoryError: PermGen space

!ENTRY org.eclipse.ui 4 0 2010-10-08 16:39:18.931
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: PermGen space
</pre>

**Comment by reprogrammer** [comment]
Have we tried  increasing `MaxPermSize` as suggested  in [news.eclipse.newcomer post](http://dev.eclipse.org/newslists/news.eclipse.newcomer/msg06139.html) and [stackoverflow](http://stackoverflow.com/questions/3743992/java-lang-outofmemoryerror-permgen-space)?

**Comment by vazexqi** [comment]
I cannot access my windows machine now but the memory settings for my launch configuration are:

-XX:MaxPermSize=256m -Xms40m -Xmx512m

**Comment by reprogrammer** [comment]
I resolved this issue in b689592ce6b7254b4b3b4b268f2854c5703f164d by increasing `MaxPermSize` on my office Windows machine using the following launch configuration settings.

`-XX:MaxPermSize=512m -Xms40m -Xmx512m`
