### ISSUE TITLE
AssertionFailedException at Eclipse shutdown.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#98]
I encountered the following exception when I closed my Eclipse. It's good to watch for it in case it shows up again.

<pre>
org.eclipse.core.runtime.AssertionFailedException: null argument:
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
    at org.eclipse.core.internal.events.ResourceChangeListenerList.remove(ResourceChangeListenerList.java:146)
    at org.eclipse.core.internal.events.NotificationManager.removeListener(NotificationManager.java:305)
    at org.eclipse.core.internal.resources.Workspace.removeResourceChangeListener(Workspace.java:1934)
    at org.eclipse.wst.server.core.internal.ResourceManager.shutdownImpl(ResourceManager.java:367)
    at org.eclipse.wst.server.core.internal.ResourceManager.shutdown(ResourceManager.java:313)
    at org.eclipse.wst.server.core.internal.ServerPlugin.stop(ServerPlugin.java:360)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl$2.run(BundleContextImpl.java:843)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.stop(BundleContextImpl.java:836)
    at org.eclipse.osgi.framework.internal.core.BundleHost.stopWorker(BundleHost.java:501)
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.suspend(AbstractBundle.java:550)
    at org.eclipse.osgi.framework.internal.core.Framework.suspendBundle(Framework.java:1097)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.decFWSL(StartLevelManager.java:597)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:257)
    at org.eclipse.osgi.framework.internal.core.StartLevelManager.shutdown(StartLevelManager.java:215)
    at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.suspend(InternalSystemBundle.java:266)
    at org.eclipse.osgi.framework.internal.core.Framework.shutdown(Framework.java:690)
    at org.eclipse.osgi.framework.internal.core.Framework.close(Framework.java:588)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.shutdown(EclipseStarter.java:415)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:198)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:619)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:574)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1407)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1383)
</pre>

**Comment by reprogrammer** [comment]
I close this issue because I don't think this exception is raised because of CodingSpectator. Besides, I don't remember seeing this exception anymore.
